'use client';

import { motion } from 'framer-motion';
import { AlertTriangle, Shield, HeartPulse, FlaskConical, Scale, Phone, BookOpen } from 'lucide-react';

// ═══════════════════════════════════════════════════════════════════════════
// ANIMATION VARIANTS
// ═══════════════════════════════════════════════════════════════════════════

const sectionVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: 'easeOut' as const } },
};

// ═══════════════════════════════════════════════════════════════════════════
// DISCLAIMER PAGE
// ═══════════════════════════════════════════════════════════════════════════

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#f8fafc] text-gray-900 antialiased">
      <main className="max-w-4xl mx-auto px-4 md:px-8 lg:px-12 py-8 w-full">
        <div className="space-y-10">

          {/* ═══ HERO ═══ */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center py-10 md:py-14 px-6 bg-white rounded-2xl border border-gray-200 shadow-lg overflow-hidden relative"
          >
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,_var(--tw-gradient-stops))] from-slate-50 via-transparent to-transparent" />
            <div className="relative z-10">
              <div className="inline-flex items-center gap-2 bg-[#0f172a] text-white px-4 py-1.5 rounded-full text-[10px] font-extrabold mb-5 tracking-[0.2em] shadow-md">
                <AlertTriangle size={12} /> DISCLAIMER
              </div>
              <h1 className="text-3xl md:text-5xl font-black text-[#0f172a] mb-3 tracking-tight leading-tight">
                Disclaimer
              </h1>
              <p className="text-gray-500 max-w-2xl mx-auto leading-relaxed text-sm md:text-base font-medium">
                Important information about the use and limitations of PharmaInsight
              </p>
            </div>
          </motion.div>

          {/* ═══ PROFESSIONAL USE NOTICE ═══ */}
          <motion.div
            variants={sectionVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-50px' }}
            className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 md:p-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-[#0f172a] rounded-lg flex items-center justify-center text-white">
                <Shield size={16} />
              </div>
              <h2 className="text-lg font-black text-[#0f172a] tracking-tight">Professional Use Notice</h2>
            </div>
            <p className="text-sm text-gray-500 leading-relaxed font-medium">
              PharmaInsight is a scientific evidence evaluation platform designed for use by researchers, healthcare professionals, academics, and regulatory professionals. The platform is intended to support literature review, evidence assessment, and scientific analysis. It is not designed for, and should not be used as, a substitute for professional medical judgment, clinical decision-making, or individualized patient care.
            </p>
          </motion.div>

          {/* ═══ NOT MEDICAL ADVICE ═══ */}
          <motion.div
            variants={sectionVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-50px' }}
            className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 md:p-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-red-600 rounded-lg flex items-center justify-center text-white">
                <HeartPulse size={16} />
              </div>
              <h2 className="text-lg font-black text-[#0f172a] tracking-tight">Not Medical Advice</h2>
            </div>
            <p className="text-sm text-gray-500 leading-relaxed font-medium">
              The information provided by PharmaInsight does not constitute medical advice, diagnosis, or treatment recommendations. All outputs generated by the platform represent structured summaries and evaluations of published scientific evidence. No output should be interpreted as a clinical recommendation for any individual patient. Healthcare decisions should always be made in consultation with qualified medical professionals who can consider the full clinical context.
            </p>
          </motion.div>

          {/* ═══ EVIDENCE LIMITATIONS ═══ */}
          <motion.div
            variants={sectionVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-50px' }}
            className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 md:p-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-amber-600 rounded-lg flex items-center justify-center text-white">
                <BookOpen size={16} />
              </div>
              <h2 className="text-lg font-black text-[#0f172a] tracking-tight">Evidence Limitations</h2>
            </div>
            <p className="text-sm text-gray-500 leading-relaxed font-medium">
              Scientific evidence is inherently subject to limitations, including but not limited to publication bias, small sample sizes, methodological heterogeneity, conflicting findings across studies, and incomplete clinical validation. PharmaInsight presents evidence as reported in the underlying literature and does not independently verify the accuracy, completeness, or clinical applicability of individual studies. Users should critically evaluate all evidence in the context of its methodological quality and the broader body of scientific knowledge.
            </p>
          </motion.div>

          {/* ═══ DRUG–HERB INTERACTION INFORMATION ═══ */}
          <motion.div
            variants={sectionVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-50px' }}
            className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 md:p-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-emerald-600 rounded-lg flex items-center justify-center text-white">
                <FlaskConical size={16} />
              </div>
              <h2 className="text-lg font-black text-[#0f172a] tracking-tight">Drug–Herb Interaction Information</h2>
            </div>
            <p className="text-sm text-gray-500 leading-relaxed font-medium">
              Drug–herb interaction assessments provided by PharmaInsight are based on available published evidence and are classified according to evidence strength and quality. These assessments are not exhaustive and may not reflect all potential interactions. The absence of a documented interaction does not confirm safety. Interaction data should be used as a starting point for further investigation and should not replace comprehensive clinical review.
            </p>
          </motion.div>

          {/* ═══ NO CLINICAL RELATIONSHIP ═══ */}
          <motion.div
            variants={sectionVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-50px' }}
            className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 md:p-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-violet-600 rounded-lg flex items-center justify-center text-white">
                <Scale size={16} />
              </div>
              <h2 className="text-lg font-black text-[#0f172a] tracking-tight">No Clinical Relationship</h2>
            </div>
            <p className="text-sm text-gray-500 leading-relaxed font-medium">
              Use of PharmaInsight does not create a doctor-patient, pharmacist-patient, or any other clinical or professional relationship between the user and the platform, its developers, or its contributors. The platform is an informational and analytical tool, and no communication through the platform constitutes professional healthcare advice.
            </p>
          </motion.div>

          {/* ═══ LIMITATION OF RESPONSIBILITY ═══ */}
          <motion.div
            variants={sectionVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-50px' }}
            className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 md:p-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-gray-600 rounded-lg flex items-center justify-center text-white">
                <AlertTriangle size={16} />
              </div>
              <h2 className="text-lg font-black text-[#0f172a] tracking-tight">Limitation of Responsibility</h2>
            </div>
            <p className="text-sm text-gray-500 leading-relaxed font-medium">
              PharmaInsight, its developers, and its contributors make no warranties, express or implied, regarding the accuracy, completeness, or fitness for any particular purpose of the information provided. To the fullest extent permitted by law, we disclaim all liability for any loss, injury, or damage arising from the use of or reliance on information obtained through the platform. Users are solely responsible for how they interpret and apply the information provided.
            </p>
          </motion.div>

          {/* ═══ EMERGENCY SITUATIONS ═══ */}
          <motion.div
            variants={sectionVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-50px' }}
            className="bg-red-50 border border-red-200 rounded-2xl p-6 md:p-8"
          >
            <div className="flex items-start gap-3">
              <div className="flex-shrink-0 w-10 h-10 bg-red-100 rounded-lg flex items-center justify-center">
                <Phone size={20} className="text-red-600" />
              </div>
              <div>
                <h3 className="font-extrabold text-[#0f172a] text-sm tracking-tight mb-2">
                  Emergency Situations
                </h3>
                <p className="text-xs text-gray-600 leading-relaxed font-medium">
                  PharmaInsight is not an emergency medical resource. If you are experiencing a medical emergency, suspected adverse drug reaction, or any urgent health concern, please contact your local emergency services, poison control center, or healthcare provider immediately. Do not rely on this platform for time-sensitive medical decisions.
                </p>
              </div>
            </div>
          </motion.div>

        </div>
      </main>
    </div>
  );
}
